In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7420, 3149, 2411, 9493],
 [7420, 3149, 2411, 5847],
 [7420, 6880, 2411, 3783],
 [8976, 9675, 3519, 5153, 3375],
 [8976, 9675, 3519, 5153, 9374],
 [393, 7420, 6447, 2411, 8372],
 [2378, 3925, 2572, 5153]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

### Setting length of all the sentences 

In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7420 3149 2411 9493]
 [   0    0    0    0 7420 3149 2411 5847]
 [   0    0    0    0 7420 6880 2411 3783]
 [   0    0    0 8976 9675 3519 5153 3375]
 [   0    0    0 8976 9675 3519 5153 9374]
 [   0    0    0  393 7420 6447 2411 8372]
 [   0    0    0    0 2378 3925 2572 5153]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\CodingStuff\MLNotes\DeepLearning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.build(input_shape=(None, sent_length))

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step


array([[[ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.04566342,  0.01207579, -0.00548064, -0.02078846,
          0.04661322,  0.04113809, -0.04758257, -0.03073128,
         -0.01657199,  0.03726469],
        [-0.0263161 , -0.01370756, -0.01470709, -0.00429733,
         -0.04733948,  0.00453072,  0.03778297, -0.01839018,
         -0.00684435,  0.0143936 ],
        [-0.04489691, -0.00545369,  0.0105303 ,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7420, 3149, 2411, 9493], dtype=int32)

In [20]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[[ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.02246127, -0.01222502,  0.02993072,  0.02558753,
          0.04837937, -0.02923943, -0.02722799, -0.02165704,
          0.0145948 ,  0.01833225],
        [ 0.04566342,  0.01207579, -0.00548064, -0.02078846,
          0.04661322,  0.04113809, -0.04758257, -0.03073128,
         -0.01657199,  0.03726469],
        [-0.0263161 , -0.01370756, -0.01470709, -0.00429733,
         -0.04733948,  0.00453072,  0.03778297, -0.01839018,
         -0.00684435,  0.0143936 ],
        [-0.04489691, -0.00545369,  0.0105303 ,  0.0